{
 "title": "default_overview",
 "description": "Default view",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "latest-ticker",
   "type": "table",
   "gridPos": { "h": 21, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT pub_date as timestamp, title, link\nFROM rss_entries\nWHERE $__timeFilter(pub_date)\nORDER BY pub_date DESC"
    }
   ]
  },
  {
   "title": "total-ingested",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM rss_entries\nWHERE $__timeFilter(pub_date)"
    }
   ]
  },
  {
   "title": "active-feeds",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT name, id, updated FROM feeds\nWHERE status = True and updated IS NOT NULL"
    }
   ]
  },
  {
   "title": "inactive-feeds",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT name, id, updated FROM feeds\nWHERE status = False and updated IS NOT NULL"
    }
   ]
  },
  {
   "title": "failed-updates",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS total_failing_feeds\nFROM feeds\nWHERE fail_reason IS NOT NULL"
    }
   ]
  },
  {
   "title": "vulns-by-mention",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  unnested_vuln AS vulnerability,\n  COUNT(*) AS \"#\"\nFROM (\n  SELECT\n    unnest(vulns) AS unnested_vuln,\n    pub_date\n  FROM rss_entries\n) subquery\nWHERE $__timeFilter(pub_date)\nGROUP BY unnested_vuln\nORDER BY \"#\" DESC;\n"
    }
   ]
  },
  {
   "title": "entries_by_source",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\n  l.latitude,\n  l.longitude,\n  l.name as location_name,\n  COUNT(e.id) as entries_count\nFROM\n  rss_entries e\nJOIN \n  feeds f ON e.feed = f.id\nJOIN\n  locations l on f.location = l.id\nWHERE\n  $__timeFilter(e.pub_date)\n  AND NOT (l.latitude = 0 and l.longitude = 0)\nGROUP BY\n  l.latitude,\n  l.longitude, l.name"
    }
   ]
  }
 ]
}